// CoinMarketCap Categories — Top 10 sectors
// Source: lib/เอกสารเพิ่มเติม/CoinMarketCap-Categories.md
// แสดงเฉพาะเหรียญที่อยู่ใน BINANCE_USDT (ซื้อขายเป็นคู่ USDT บน Binance)

export type CryptoCoin = {
  name: string;
  symbol: string;
};

export type CryptoCategory = {
  id: string;
  name: string;
  emoji: string;
  description: string;
  url: string;
  coins: CryptoCoin[];
};

// Binance USDT spot pairs (allow-list)
// ถ้าต้องการเพิ่มเหรียญในหมวดด้านล่าง ต้องเพิ่ม symbol ที่นี่ก่อน
export const BINANCE_USDT = new Set<string>([
  // L1 / Major
  "BTC", "ETH", "BNB", "SOL", "XRP", "ADA", "DOGE", "AVAX", "DOT", "LINK",
  "POL", "MATIC", "LTC", "ATOM", "NEAR", "APT", "ARB", "OP", "SUI", "INJ",
  "FET", "TRX", "TON", "HBAR", "BCH", "ETC", "XLM", "ALGO", "VET", "ICP",
  "TIA", "SEI", "FIL", "AAVE", "UNI", "RENDER", "IMX", "MKR", "TAO", "JUP",
  // Stablecoins (Binance spot pairs)
  "USDC", "DAI", "TUSD", "FDUSD", "USDP", "USDE",
  // DeFi
  "JTO", "PYTH", "ZRO", "ENA", "LDO", "CRV", "COMP", "CAKE", "1INCH", "SNX",
  "GMX", "RUNE", "ETHFI", "PENDLE", "SAFE", "MORPHO", "AERO", "USUAL",
  "WLD", "QNT", "JST", "DEXE", "EDGE", "HYPE",
  // AI / Big Data
  "KAITO", "IO", "VANA", "ZETA", "BAT", "GRT", "THETA", "ROSE", "IOTX",
  "GLM", "ATH", "AKT", "VIRTUAL", "GRASS", "AIOZ", "IP", "TRAC", "EGLD",
  "LPT", "NMR",
  // Memes
  "SHIB", "PEPE", "BONK", "WIF", "FLOKI", "TURBO", "BRETT", "NEIRO",
  "MOODENG", "POPCAT", "PNUT", "NOT", "FARTCOIN", "PENGU", "TRUMP",
  "DEGEN", "APE", "MOG", "BABYDOGE", "MEW", "ELON", "PONKE", "M",
  // Gaming
  "SAND", "MANA", "AXS", "GALA", "ENJ", "ZIL", "RON", "SUPER", "ILV",
  "WAXP", "YGG", "CHZ", "BEAM", "WEMIX", "STX",
  // L2
  "MNT", "STRK", "ZK", "CKB", "ASTR", "ALT", "MANTA", "COTI", "PHA",
  "CTSI", "MTL", "CELO", "SNT", "LSK", "LINEA",
  // Privacy
  "ZEC", "DASH", "XTZ", "MINA", "DUSK",
  // RWA
  "PAXG",
  // Smart Contracts
  "NEO", "QTUM", "GAS", "ZEN", "XDC", "MON",
  // Solana ecosystem extras
  "RAY", "PUMP", "TWT", "ENS", "LUNC",
]);

export function isBinanceListed(symbol: string): boolean {
  return BINANCE_USDT.has(symbol.toUpperCase());
}

// ─── หมวดหมู่ (pre-filtered ตาม BINANCE_USDT) ──────────────────
// ทุกเหรียญในนี้ผ่านการตรวจ isBinanceListed() แล้ว
export const CRYPTO_CATEGORIES: CryptoCategory[] = [
  {
    id: "l1-major",
    name: "L1 / Major",
    emoji: "👑",
    description: "Layer 1 หลักและเหรียญยอดนิยมที่ Market Cap สูง",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Bitcoin", symbol: "BTC" },
      { name: "Ethereum", symbol: "ETH" },
      { name: "BNB", symbol: "BNB" },
      { name: "Solana", symbol: "SOL" },
      { name: "XRP", symbol: "XRP" },
      { name: "Cardano", symbol: "ADA" },
      { name: "Dogecoin", symbol: "DOGE" },
      { name: "Avalanche", symbol: "AVAX" },
      { name: "Polkadot", symbol: "DOT" },
      { name: "Chainlink", symbol: "LINK" },
      { name: "Polygon", symbol: "POL" },
      { name: "Polygon (Old)", symbol: "MATIC" },
      { name: "Litecoin", symbol: "LTC" },
      { name: "Cosmos", symbol: "ATOM" },
      { name: "NEAR Protocol", symbol: "NEAR" },
      { name: "Aptos", symbol: "APT" },
      { name: "Arbitrum", symbol: "ARB" },
      { name: "Optimism", symbol: "OP" },
      { name: "Sui", symbol: "SUI" },
      { name: "Injective", symbol: "INJ" },
      { name: "Fetch.ai (ASI)", symbol: "FET" },
      { name: "TRON", symbol: "TRX" },
      { name: "Toncoin", symbol: "TON" },
      { name: "Hedera", symbol: "HBAR" },
      { name: "Bitcoin Cash", symbol: "BCH" },
      { name: "Ethereum Classic", symbol: "ETC" },
      { name: "Stellar", symbol: "XLM" },
      { name: "Algorand", symbol: "ALGO" },
      { name: "VeChain", symbol: "VET" },
      { name: "Internet Computer", symbol: "ICP" },
      { name: "Celestia", symbol: "TIA" },
      { name: "Sei", symbol: "SEI" },
      { name: "Filecoin", symbol: "FIL" },
      { name: "Aave", symbol: "AAVE" },
      { name: "Uniswap", symbol: "UNI" },
      { name: "Render", symbol: "RENDER" },
      { name: "Immutable", symbol: "IMX" },
      { name: "Maker", symbol: "MKR" },
      { name: "Bittensor", symbol: "TAO" },
      { name: "Jupiter", symbol: "JUP" },
    ],
  },
  {
    id: "defi",
    name: "DeFi",
    emoji: "🏦",
    description: "Lending, DEX, Yield Farming, Derivatives — ระบบการเงินไร้ตัวกลาง",
    url: "https://coinmarketcap.com/view/defi/",
    coins: [
      { name: "Hyperliquid", symbol: "HYPE" },
      { name: "Chainlink", symbol: "LINK" },
      { name: "Dai", symbol: "DAI" },
      { name: "Stellar", symbol: "XLM" },
      { name: "Uniswap", symbol: "UNI" },
      { name: "Polkadot", symbol: "DOT" },
      { name: "Aave", symbol: "AAVE" },
      { name: "DeXe", symbol: "DEXE" },
      { name: "Cosmos", symbol: "ATOM" },
      { name: "Render", symbol: "RENDER" },
      { name: "Morpho", symbol: "MORPHO" },
      { name: "Worldcoin", symbol: "WLD" },
      { name: "Ethena", symbol: "ENA" },
      { name: "Quant", symbol: "QNT" },
      { name: "JUST", symbol: "JST" },
      { name: "Jupiter", symbol: "JUP" },
      { name: "edgeX", symbol: "EDGE" },
      { name: "PancakeSwap", symbol: "CAKE" },
      { name: "LayerZero", symbol: "ZRO" },
      { name: "Aerodrome Finance", symbol: "AERO" },
      { name: "Curve DAO", symbol: "CRV" },
      { name: "ether.fi", symbol: "ETHFI" },
      { name: "Pyth Network", symbol: "PYTH" },
      { name: "Pendle", symbol: "PENDLE" },
      { name: "Lido DAO", symbol: "LDO" },
      { name: "The Graph", symbol: "GRT" },
      { name: "Jito", symbol: "JTO" },
    ],
  },
  {
    id: "ai-big-data",
    name: "AI & Big Data",
    emoji: "🤖",
    description: "AI agents, GPU compute, decentralized data, ML platforms",
    url: "https://coinmarketcap.com/view/ai-big-data/",
    coins: [
      { name: "Bittensor", symbol: "TAO" },
      { name: "NEAR Protocol", symbol: "NEAR" },
      { name: "Internet Computer", symbol: "ICP" },
      { name: "DeXe", symbol: "DEXE" },
      { name: "Render", symbol: "RENDER" },
      { name: "Filecoin", symbol: "FIL" },
      { name: "Injective", symbol: "INJ" },
      { name: "Virtuals Protocol", symbol: "VIRTUAL" },
      { name: "Artificial Superintelligence", symbol: "FET" },
      { name: "The Graph", symbol: "GRT" },
      { name: "Akash Network", symbol: "AKT" },
      { name: "OriginTrail", symbol: "TRAC" },
      { name: "Theta Network", symbol: "THETA" },
      { name: "Story Protocol", symbol: "IP" },
      { name: "Basic Attention", symbol: "BAT" },
      { name: "Golem", symbol: "GLM" },
      { name: "Aethir", symbol: "ATH" },
      { name: "Kaito", symbol: "KAITO" },
      { name: "MultiversX", symbol: "EGLD" },
      { name: "Livepeer", symbol: "LPT" },
      { name: "Grass", symbol: "GRASS" },
      { name: "AIOZ Network", symbol: "AIOZ" },
      { name: "Oasis Network", symbol: "ROSE" },
      { name: "ZetaChain", symbol: "ZETA" },
      { name: "Numeraire", symbol: "NMR" },
      { name: "io.net", symbol: "IO" },
      { name: "Vana", symbol: "VANA" },
      { name: "IoTeX", symbol: "IOTX" },
    ],
  },
  {
    id: "memes",
    name: "Memes",
    emoji: "🐶",
    description: "เหรียญที่ขับเคลื่อนด้วยกระแสและ community",
    url: "https://coinmarketcap.com/view/memes/",
    coins: [
      { name: "Dogecoin", symbol: "DOGE" },
      { name: "MemeCore", symbol: "M" },
      { name: "Shiba Inu", symbol: "SHIB" },
      { name: "Pepe", symbol: "PEPE" },
      { name: "Pudgy Penguins", symbol: "PENGU" },
      { name: "Bonk", symbol: "BONK" },
      { name: "Official Trump", symbol: "TRUMP" },
      { name: "FLOKI", symbol: "FLOKI" },
      { name: "dogwifhat", symbol: "WIF" },
      { name: "ApeCoin", symbol: "APE" },
      { name: "Fartcoin", symbol: "FARTCOIN" },
      { name: "Brett", symbol: "BRETT" },
      { name: "Turbo", symbol: "TURBO" },
      { name: "Baby Doge Coin", symbol: "BABYDOGE" },
      { name: "Peanut the Squirrel", symbol: "PNUT" },
      { name: "Mog Coin", symbol: "MOG" },
      { name: "Popcat", symbol: "POPCAT" },
      { name: "Moo Deng", symbol: "MOODENG" },
      { name: "Notcoin", symbol: "NOT" },
      { name: "Neiro", symbol: "NEIRO" },
      { name: "Dogelon Mars", symbol: "ELON" },
      { name: "Ponke", symbol: "PONKE" },
      { name: "Degen", symbol: "DEGEN" },
    ],
  },
  {
    id: "gaming",
    name: "Gaming",
    emoji: "🎮",
    description: "Play-to-earn, metaverse, gaming tokens",
    url: "https://coinmarketcap.com/view/gaming/",
    coins: [
      { name: "Render", symbol: "RENDER" },
      { name: "Virtuals Protocol", symbol: "VIRTUAL" },
      { name: "Stacks", symbol: "STX" },
      { name: "Immutable", symbol: "IMX" },
      { name: "FLOKI", symbol: "FLOKI" },
      { name: "The Sandbox", symbol: "SAND" },
      { name: "Axie Infinity", symbol: "AXS" },
      { name: "Decentraland", symbol: "MANA" },
      { name: "Gala", symbol: "GALA" },
      { name: "ApeCoin", symbol: "APE" },
      { name: "Wemix", symbol: "WEMIX" },
      { name: "MultiversX", symbol: "EGLD" },
      { name: "Beam", symbol: "BEAM" },
      { name: "Enjin Coin", symbol: "ENJ" },
      { name: "Zilliqa", symbol: "ZIL" },
      { name: "Ronin", symbol: "RON" },
      { name: "SuperVerse", symbol: "SUPER" },
      { name: "Baby Doge Coin", symbol: "BABYDOGE" },
      { name: "Illuvium", symbol: "ILV" },
      { name: "Wax", symbol: "WAXP" },
      { name: "Yield Guild Games", symbol: "YGG" },
      { name: "Chiliz", symbol: "CHZ" },
    ],
  },
  {
    id: "layer-2",
    name: "Layer 2",
    emoji: "⚡",
    description: "โซลูชันขยายความสามารถบน L1 (เร็วและถูกกว่า)",
    url: "https://coinmarketcap.com/view/layer-2/",
    coins: [
      { name: "Mantle", symbol: "MNT" },
      { name: "Polygon", symbol: "POL" },
      { name: "Arbitrum", symbol: "ARB" },
      { name: "Stacks", symbol: "STX" },
      { name: "Immutable", symbol: "IMX" },
      { name: "Optimism", symbol: "OP" },
      { name: "Starknet", symbol: "STRK" },
      { name: "ZKsync", symbol: "ZK" },
      { name: "Nervos Network", symbol: "CKB" },
      { name: "Astar", symbol: "ASTR" },
      { name: "Altlayer", symbol: "ALT" },
      { name: "Linea", symbol: "LINEA" },
      { name: "Celo", symbol: "CELO" },
      { name: "Status", symbol: "SNT" },
      { name: "Manta Network", symbol: "MANTA" },
      { name: "COTI", symbol: "COTI" },
      { name: "Phala Network", symbol: "PHA" },
      { name: "Lisk", symbol: "LSK" },
      { name: "Cartesi", symbol: "CTSI" },
      { name: "Metal DAO", symbol: "MTL" },
    ],
  },
  {
    id: "privacy",
    name: "Privacy",
    emoji: "🔒",
    description: "เหรียญเน้นความเป็นส่วนตัว (AECs) — ปกปิดธุรกรรม/identity",
    url: "https://coinmarketcap.com/view/privacy/",
    coins: [
      { name: "Zcash", symbol: "ZEC" },
      { name: "Chainlink", symbol: "LINK" },
      { name: "Litecoin", symbol: "LTC" },
      { name: "Dash", symbol: "DASH" },
      { name: "Tezos", symbol: "XTZ" },
      { name: "Starknet", symbol: "STRK" },
      { name: "OriginTrail", symbol: "TRAC" },
      { name: "ZKsync", symbol: "ZK" },
      { name: "Oasis", symbol: "ROSE" },
      { name: "Mina", symbol: "MINA" },
      { name: "Dusk", symbol: "DUSK" },
      { name: "Celo", symbol: "CELO" },
      { name: "Status", symbol: "SNT" },
    ],
  },
  {
    id: "rwa",
    name: "RWA",
    emoji: "🏛️",
    description: "Token อ้างอิงสินทรัพย์จริง (ทอง หุ้น ETF พันธบัตร)",
    url: "https://coinmarketcap.com/view/tokenized-assets/",
    coins: [
      { name: "PAX Gold", symbol: "PAXG" },
    ],
  },
  {
    id: "solana-ecosystem",
    name: "Solana Eco",
    emoji: "☀️",
    description: "โปรเจกต์/Token บน Solana blockchain",
    url: "https://coinmarketcap.com/view/solana-ecosystem/",
    coins: [
      { name: "XRP", symbol: "XRP" },
      { name: "Solana", symbol: "SOL" },
      { name: "Chainlink", symbol: "LINK" },
      { name: "Uniswap", symbol: "UNI" },
      { name: "Aave", symbol: "AAVE" },
      { name: "Render", symbol: "RENDER" },
      { name: "Jupiter", symbol: "JUP" },
      { name: "Pump.fun", symbol: "PUMP" },
      { name: "Pudgy Penguins", symbol: "PENGU" },
      { name: "Bonk", symbol: "BONK" },
      { name: "Virtuals Protocol", symbol: "VIRTUAL" },
      { name: "Official Trump", symbol: "TRUMP" },
      { name: "PancakeSwap", symbol: "CAKE" },
      { name: "Terra Classic", symbol: "LUNC" },
      { name: "Pyth Network", symbol: "PYTH" },
      { name: "Lido DAO", symbol: "LDO" },
      { name: "The Graph", symbol: "GRT" },
      { name: "ENS", symbol: "ENS" },
      { name: "Jito", symbol: "JTO" },
      { name: "Compound", symbol: "COMP" },
      { name: "Axie Infinity", symbol: "AXS" },
      { name: "Raydium", symbol: "RAY" },
      { name: "dogwifhat", symbol: "WIF" },
      { name: "Trust Wallet", symbol: "TWT" },
      { name: "Fartcoin", symbol: "FARTCOIN" },
    ],
  },
  {
    id: "smart-contracts",
    name: "Smart Contracts",
    emoji: "📜",
    description: "Blockchain ที่รัน smart contracts (Layer 1 platforms)",
    url: "https://coinmarketcap.com/view/smart-contracts/",
    coins: [
      { name: "Ethereum", symbol: "ETH" },
      { name: "BNB", symbol: "BNB" },
      { name: "Cardano", symbol: "ADA" },
      { name: "Chainlink", symbol: "LINK" },
      { name: "Stellar", symbol: "XLM" },
      { name: "Avalanche", symbol: "AVAX" },
      { name: "Internet Computer", symbol: "ICP" },
      { name: "Ethereum Classic", symbol: "ETC" },
      { name: "Algorand", symbol: "ALGO" },
      { name: "XDC Network", symbol: "XDC" },
      { name: "VeChain", symbol: "VET" },
      { name: "Injective", symbol: "INJ" },
      { name: "PancakeSwap", symbol: "CAKE" },
      { name: "Stacks", symbol: "STX" },
      { name: "Tezos", symbol: "XTZ" },
      { name: "Monad", symbol: "MON" },
      { name: "Starknet", symbol: "STRK" },
      { name: "OriginTrail", symbol: "TRAC" },
      { name: "Theta Network", symbol: "THETA" },
      { name: "Neo", symbol: "NEO" },
      { name: "Story", symbol: "IP" },
      { name: "Basic Attention", symbol: "BAT" },
      { name: "MultiversX", symbol: "EGLD" },
      { name: "Horizen", symbol: "ZEN" },
      { name: "Gas", symbol: "GAS" },
      { name: "Qtum", symbol: "QTUM" },
    ],
  },
];
