// Binance USDT spot categories
// ทุก symbol ในไฟล์นี้ตรวจกับ GET /api/v3/exchangeInfo แล้วว่า status=TRADING จริง
// (รอบก่อนหน้ามี 30 จาก 148 เหรียญที่ถูกถอดไปแล้วแต่ยังค้างอยู่ใน list)
//
// รายชื่อนี้เป็นชุด "คัดมาแล้ว" สำหรับเลือกตามหมวด — ถ้าต้องการเหรียญทั้งหมดที่
// เทรดได้ตอนนี้ ให้ใช้ /api/binance/usdt-symbols ซึ่งดึงสดจาก Binance

export type CryptoCoin = {
  name: string;
  symbol: string;
};

export type CryptoCategory = {
  id: string;
  name: string;
  emoji: string;
  description: string;
  url: string;
  coins: CryptoCoin[];
};

// allow-list — union ของทุกหมวดด้านล่าง
export const BINANCE_USDT = new Set<string>([
  "1000SATS", "1INCH", "AAVE", "ACE", "ACT", "ADA", "AERO", "AEUR", "AI", "ALGO",
  "ALICE", "ALLO", "ALT", "ANKR", "APE", "API3", "APT", "AR", "ARB", "ARKM",
  "ARPA", "ASTR", "ATOM", "AVAX", "AXS", "BANANAS31", "BAND", "BCH", "BERA", "BFUSD",
  "BIGTIME", "BLUR", "BNB", "BOME", "BONK", "BROCCOLI714", "BTC", "CAKE", "CELO", "CFG",
  "CFX", "CHZ", "CKB", "COMP", "COTI", "CRV", "CTSI", "DASH", "DEXE", "DOGE",
  "DOT", "DUSK", "DYDX", "EGLD", "EIGEN", "ENA", "ENJ", "ETC", "ETH", "ETHFI",
  "EURI", "FDUSD", "FET", "FIL", "FLOKI", "FLOW", "FLUX", "GALA", "GAS", "GIGGLE",
  "GLM", "GMT", "GMX", "GNS", "GRT", "HBAR", "HFT", "HOME", "HOT", "HYPER",
  "ICP", "ILV", "IMX", "INJ", "IO", "IOTA", "IOTX", "JASMY", "JOE", "JTO",
  "JUP", "KAIA", "KAITO", "KAVA", "KMNO", "LAYER", "LDO", "LINEA", "LINK", "LPT",
  "LQTY", "LSK", "LTC", "MAGIC", "MANA", "MANTA", "ME", "MEME", "METIS", "MINA",
  "MORPHO", "MOVE", "MUBARAK", "NEAR", "NEIRO", "NEO", "NMR", "NOT", "ONDO", "ONE",
  "OP", "OPEN", "ORCA", "PAXG", "PENDLE", "PENGU", "PEPE", "PHA", "PIXEL", "PLUME",
  "PNUT", "POL", "POLYX", "PORTAL", "POWR", "PUMP", "PYTH", "QNT", "QTUM", "RARE",
  "RAY", "RED", "RENDER", "RESOLV", "RLUSD", "ROSE", "RPL", "RSR", "RUNE", "S",
  "SAHARA", "SAND", "SC", "SCR", "SCRT", "SEI", "SHIB", "SKL", "SKY", "SLP",
  "SNX", "SOL", "SOLV", "SPELL", "STORJ", "STRK", "STX", "SUI", "SUPER", "SUSHI",
  "SYRUP", "TAO", "THETA", "TIA", "TLM", "TNSR", "TRB", "TREE", "TRUMP", "TRX",
  "TST", "TURBO", "TUSD", "UNI", "USD1", "USDC", "USDE", "USDP", "USUAL", "VANA",
  "VET", "VIRTUAL", "W", "WAXP", "WIF", "WLD", "XAI", "XAUT", "XLM", "XRP",
  "XTZ", "XUSD", "XVG", "YFI", "YGG", "ZEC", "ZEN", "ZIL", "ZK", "ZRO",
  "ZRX",
]);

export function isBinanceListed(symbol: string): boolean {
  return BINANCE_USDT.has(symbol.toUpperCase());
}

export const CRYPTO_CATEGORIES: CryptoCategory[] = [
  {
    id: "l1-major",
    name: "L1 / Major",
    emoji: "👑",
    description: "Layer 1 หลักและเหรียญ Market Cap สูง",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Bitcoin", symbol: "BTC" },
      { name: "Ethereum", symbol: "ETH" },
      { name: "BNB", symbol: "BNB" },
      { name: "Solana", symbol: "SOL" },
      { name: "XRP", symbol: "XRP" },
      { name: "Cardano", symbol: "ADA" },
      { name: "Dogecoin", symbol: "DOGE" },
      { name: "Avalanche", symbol: "AVAX" },
      { name: "Polkadot", symbol: "DOT" },
      { name: "Chainlink", symbol: "LINK" },
      { name: "Polygon", symbol: "POL" },
      { name: "Litecoin", symbol: "LTC" },
      { name: "Cosmos", symbol: "ATOM" },
      { name: "NEAR Protocol", symbol: "NEAR" },
      { name: "Aptos", symbol: "APT" },
      { name: "Arbitrum", symbol: "ARB" },
      { name: "Optimism", symbol: "OP" },
      { name: "Sui", symbol: "SUI" },
      { name: "Injective", symbol: "INJ" },
      { name: "Artificial Superintelligence", symbol: "FET" },
      { name: "TRON", symbol: "TRX" },
      { name: "Hedera", symbol: "HBAR" },
      { name: "Bitcoin Cash", symbol: "BCH" },
      { name: "Ethereum Classic", symbol: "ETC" },
      { name: "Stellar", symbol: "XLM" },
      { name: "Algorand", symbol: "ALGO" },
      { name: "VeChain", symbol: "VET" },
      { name: "Internet Computer", symbol: "ICP" },
      { name: "Celestia", symbol: "TIA" },
      { name: "Sei", symbol: "SEI" },
      { name: "Filecoin", symbol: "FIL" },
      { name: "Aave", symbol: "AAVE" },
      { name: "Uniswap", symbol: "UNI" },
      { name: "Render", symbol: "RENDER" },
      { name: "Immutable", symbol: "IMX" },
      { name: "Bittensor", symbol: "TAO" },
      { name: "Jupiter", symbol: "JUP" },
      { name: "Sonic", symbol: "S" },
      { name: "SushiSwap", symbol: "SUSHI" },
      { name: "MultiversX", symbol: "EGLD" },
      { name: "Flow", symbol: "FLOW" },
      { name: "Tezos", symbol: "XTZ" },
      { name: "Neo", symbol: "NEO" },
      { name: "IOTA", symbol: "IOTA" },
      { name: "Zcash", symbol: "ZEC" },
      { name: "Dash", symbol: "DASH" },
      { name: "Quant", symbol: "QNT" },
      { name: "Stacks", symbol: "STX" },
      { name: "Theta Network", symbol: "THETA" },
      { name: "Mina", symbol: "MINA" },
      { name: "Oasis", symbol: "ROSE" },
      { name: "Conflux", symbol: "CFX" },
      { name: "Kava", symbol: "KAVA" },
      { name: "Harmony", symbol: "ONE" },
      { name: "Zilliqa", symbol: "ZIL" },
      { name: "Worldcoin", symbol: "WLD" },
      { name: "Ethena", symbol: "ENA" },
      { name: "Ondo", symbol: "ONDO" },
      { name: "Berachain", symbol: "BERA" },
      { name: "Pudgy Penguins", symbol: "PENGU" },
      { name: "Official Trump", symbol: "TRUMP" },
      { name: "Virtuals Protocol", symbol: "VIRTUAL" },
      { name: "Movement", symbol: "MOVE" },
      { name: "Magic Eden", symbol: "ME" },
      { name: "Solayer", symbol: "LAYER" },
      { name: "Kaia", symbol: "KAIA" },
      { name: "Pyth Network", symbol: "PYTH" },
    ],
  },
  {
    id: "defi",
    name: "DeFi",
    emoji: "🏦",
    description: "โปรโตคอลการเงินไร้ตัวกลาง — lending, DEX, ตราสารอนุพันธ์",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Uniswap", symbol: "UNI" },
      { name: "Aave", symbol: "AAVE" },
      { name: "Chainlink", symbol: "LINK" },
      { name: "Curve DAO", symbol: "CRV" },
      { name: "Compound", symbol: "COMP" },
      { name: "PancakeSwap", symbol: "CAKE" },
      { name: "1INCH", symbol: "1INCH" },
      { name: "SNX", symbol: "SNX" },
      { name: "GMX", symbol: "GMX" },
      { name: "RUNE", symbol: "RUNE" },
      { name: "ether.fi", symbol: "ETHFI" },
      { name: "Pendle", symbol: "PENDLE" },
      { name: "Morpho", symbol: "MORPHO" },
      { name: "Aerodrome Finance", symbol: "AERO" },
      { name: "USUAL", symbol: "USUAL" },
      { name: "Lido DAO", symbol: "LDO" },
      { name: "Jito", symbol: "JTO" },
      { name: "Pyth Network", symbol: "PYTH" },
      { name: "LayerZero", symbol: "ZRO" },
      { name: "Ethena", symbol: "ENA" },
      { name: "dYdX", symbol: "DYDX" },
      { name: "Trader Joe", symbol: "JOE" },
      { name: "Raydium", symbol: "RAY" },
      { name: "SushiSwap", symbol: "SUSHI" },
      { name: "yearn.finance", symbol: "YFI" },
      { name: "Liquity", symbol: "LQTY" },
      { name: "Spell", symbol: "SPELL" },
      { name: "Kamino", symbol: "KMNO" },
      { name: "Hyperlane", symbol: "HYPER" },
      { name: "EigenLayer", symbol: "EIGEN" },
      { name: "Ondo", symbol: "ONDO" },
      { name: "Maple", symbol: "SYRUP" },
      { name: "Resolv", symbol: "RESOLV" },
      { name: "Sky", symbol: "SKY" },
      { name: "Treehouse", symbol: "TREE" },
    ],
  },
  {
    id: "ai-big-data",
    name: "AI & Big Data",
    emoji: "🤖",
    description: "เหรียญสาย AI, machine learning และเครือข่ายข้อมูล",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Bittensor", symbol: "TAO" },
      { name: "Render", symbol: "RENDER" },
      { name: "Artificial Superintelligence", symbol: "FET" },
      { name: "The Graph", symbol: "GRT" },
      { name: "Theta Network", symbol: "THETA" },
      { name: "Oasis", symbol: "ROSE" },
      { name: "IoTeX", symbol: "IOTX" },
      { name: "Golem", symbol: "GLM" },
      { name: "Numeraire", symbol: "NMR" },
      { name: "Livepeer", symbol: "LPT" },
      { name: "Arkham", symbol: "ARKM" },
      { name: "Worldcoin", symbol: "WLD" },
      { name: "Virtuals Protocol", symbol: "VIRTUAL" },
      { name: "io.net", symbol: "IO" },
      { name: "Kaito", symbol: "KAITO" },
      { name: "Sleepless AI", symbol: "AI" },
      { name: "Turbo", symbol: "TURBO" },
      { name: "Vana", symbol: "VANA" },
      { name: "Sahara AI", symbol: "SAHARA" },
      { name: "OpenLedger", symbol: "OPEN" },
      { name: "Allora", symbol: "ALLO" },
    ],
  },
  {
    id: "memes",
    name: "Memes",
    emoji: "🐶",
    description: "เหรียญมีมที่ราคาขับเคลื่อนด้วยกระแส — ผันผวนสูงมาก",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Dogecoin", symbol: "DOGE" },
      { name: "Shiba Inu", symbol: "SHIB" },
      { name: "Pepe", symbol: "PEPE" },
      { name: "Bonk", symbol: "BONK" },
      { name: "dogwifhat", symbol: "WIF" },
      { name: "FLOKI", symbol: "FLOKI" },
      { name: "Turbo", symbol: "TURBO" },
      { name: "Neiro", symbol: "NEIRO" },
      { name: "Peanut the Squirrel", symbol: "PNUT" },
      { name: "Notcoin", symbol: "NOT" },
      { name: "Pudgy Penguins", symbol: "PENGU" },
      { name: "Official Trump", symbol: "TRUMP" },
      { name: "ApeCoin", symbol: "APE" },
      { name: "Memecoin", symbol: "MEME" },
      { name: "SATS", symbol: "1000SATS" },
      { name: "Act I", symbol: "ACT" },
      { name: "BOOK OF MEME", symbol: "BOME" },
      { name: "MUBARAK", symbol: "MUBARAK" },
      { name: "Broccoli", symbol: "BROCCOLI714" },
      { name: "Banana For Scale", symbol: "BANANAS31" },
      { name: "Test", symbol: "TST" },
      { name: "Giggle", symbol: "GIGGLE" },
      { name: "Smooth Love Potion", symbol: "SLP" },
    ],
  },
  {
    id: "gaming",
    name: "Gaming",
    emoji: "🎮",
    description: "เกมบล็อกเชนและ GameFi",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "The Sandbox", symbol: "SAND" },
      { name: "Decentraland", symbol: "MANA" },
      { name: "Axie Infinity", symbol: "AXS" },
      { name: "Gala", symbol: "GALA" },
      { name: "Enjin Coin", symbol: "ENJ" },
      { name: "Zilliqa", symbol: "ZIL" },
      { name: "SuperVerse", symbol: "SUPER" },
      { name: "Illuvium", symbol: "ILV" },
      { name: "Wax", symbol: "WAXP" },
      { name: "Yield Guild Games", symbol: "YGG" },
      { name: "Chiliz", symbol: "CHZ" },
      { name: "Stacks", symbol: "STX" },
      { name: "Pixels", symbol: "PIXEL" },
      { name: "Portal", symbol: "PORTAL" },
      { name: "Fusionist", symbol: "ACE" },
      { name: "Magic", symbol: "MAGIC" },
      { name: "MyNeighborAlice", symbol: "ALICE" },
      { name: "Alien Worlds", symbol: "TLM" },
      { name: "Big Time", symbol: "BIGTIME" },
      { name: "STEPN", symbol: "GMT" },
      { name: "SKALE", symbol: "SKL" },
      { name: "Xai", symbol: "XAI" },
    ],
  },
  {
    id: "layer-2",
    name: "Layer 2",
    emoji: "⚡",
    description: "เครือข่ายขยายขนาดที่รันบน L1 อีกที",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Arbitrum", symbol: "ARB" },
      { name: "Optimism", symbol: "OP" },
      { name: "Starknet", symbol: "STRK" },
      { name: "ZKsync", symbol: "ZK" },
      { name: "Nervos Network", symbol: "CKB" },
      { name: "Astar", symbol: "ASTR" },
      { name: "Altlayer", symbol: "ALT" },
      { name: "Manta Network", symbol: "MANTA" },
      { name: "COTI", symbol: "COTI" },
      { name: "Phala Network", symbol: "PHA" },
      { name: "Cartesi", symbol: "CTSI" },
      { name: "Celo", symbol: "CELO" },
      { name: "Lisk", symbol: "LSK" },
      { name: "Linea", symbol: "LINEA" },
      { name: "Metis", symbol: "METIS" },
      { name: "Scroll", symbol: "SCR" },
      { name: "Movement", symbol: "MOVE" },
      { name: "SKALE", symbol: "SKL" },
      { name: "Immutable", symbol: "IMX" },
      { name: "Polygon", symbol: "POL" },
    ],
  },
  {
    id: "privacy",
    name: "Privacy",
    emoji: "🔒",
    description: "เหรียญที่เน้นความเป็นส่วนตัวของธุรกรรม",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Zcash", symbol: "ZEC" },
      { name: "Dash", symbol: "DASH" },
      { name: "Tezos", symbol: "XTZ" },
      { name: "Mina", symbol: "MINA" },
      { name: "Dusk", symbol: "DUSK" },
      { name: "Secret", symbol: "SCRT" },
      { name: "Oasis", symbol: "ROSE" },
      { name: "ARPA", symbol: "ARPA" },
      { name: "Verge", symbol: "XVG" },
    ],
  },
  {
    id: "rwa",
    name: "RWA",
    emoji: "🏛️",
    description: "สินทรัพย์โลกจริงบนบล็อกเชน — ทองคำ, พันธบัตร, เครดิต",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "PAX Gold", symbol: "PAXG" },
      { name: "Ondo", symbol: "ONDO" },
      { name: "USUAL", symbol: "USUAL" },
      { name: "Polymesh", symbol: "POLYX" },
      { name: "Centrifuge", symbol: "CFG" },
      { name: "Reserve Rights", symbol: "RSR" },
      { name: "Plume", symbol: "PLUME" },
      { name: "Defi App", symbol: "HOME" },
      { name: "Tether Gold", symbol: "XAUT" },
    ],
  },
  {
    id: "solana-ecosystem",
    name: "Solana Eco",
    emoji: "☀️",
    description: "โปรเจกต์ที่สร้างบน Solana",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Solana", symbol: "SOL" },
      { name: "Jupiter", symbol: "JUP" },
      { name: "Raydium", symbol: "RAY" },
      { name: "Jito", symbol: "JTO" },
      { name: "Pyth Network", symbol: "PYTH" },
      { name: "dogwifhat", symbol: "WIF" },
      { name: "Bonk", symbol: "BONK" },
      { name: "Pudgy Penguins", symbol: "PENGU" },
      { name: "Kamino", symbol: "KMNO" },
      { name: "Magic Eden", symbol: "ME" },
      { name: "Tensor", symbol: "TNSR" },
      { name: "Orca", symbol: "ORCA" },
      { name: "Wormhole", symbol: "W" },
      { name: "io.net", symbol: "IO" },
      { name: "Official Trump", symbol: "TRUMP" },
      { name: "Pump.fun", symbol: "PUMP" },
    ],
  },
  {
    id: "smart-contracts",
    name: "Smart Contracts",
    emoji: "📜",
    description: "แพลตฟอร์มที่รัน smart contract ได้",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Ethereum", symbol: "ETH" },
      { name: "Cardano", symbol: "ADA" },
      { name: "Solana", symbol: "SOL" },
      { name: "Avalanche", symbol: "AVAX" },
      { name: "Polkadot", symbol: "DOT" },
      { name: "NEAR Protocol", symbol: "NEAR" },
      { name: "Algorand", symbol: "ALGO" },
      { name: "MultiversX", symbol: "EGLD" },
      { name: "Neo", symbol: "NEO" },
      { name: "Qtum", symbol: "QTUM" },
      { name: "Gas", symbol: "GAS" },
      { name: "Horizen", symbol: "ZEN" },
      { name: "Internet Computer", symbol: "ICP" },
      { name: "TRON", symbol: "TRX" },
      { name: "Kava", symbol: "KAVA" },
      { name: "Harmony", symbol: "ONE" },
      { name: "Flow", symbol: "FLOW" },
      { name: "Sei", symbol: "SEI" },
      { name: "Celestia", symbol: "TIA" },
      { name: "Sonic", symbol: "S" },
      { name: "Berachain", symbol: "BERA" },
      { name: "Kaia", symbol: "KAIA" },
      { name: "Movement", symbol: "MOVE" },
    ],
  },
  {
    id: "stablecoins",
    name: "Stablecoins",
    emoji: "💵",
    description: "เหรียญตรึงมูลค่า — ใช้ทดสอบระบบ ไม่เหมาะเทรดตามสัญญาณ",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "USD Coin", symbol: "USDC" },
      { name: "First Digital USD", symbol: "FDUSD" },
      { name: "World Liberty USD", symbol: "USD1" },
      { name: "Ripple USD", symbol: "RLUSD" },
      { name: "TrueUSD", symbol: "TUSD" },
      { name: "Pax Dollar", symbol: "USDP" },
      { name: "Eurite", symbol: "EURI" },
      { name: "StraitsX USD", symbol: "XUSD" },
      { name: "Anchored EUR", symbol: "AEUR" },
      { name: "Ethena USDe", symbol: "USDE" },
      { name: "BFUSD", symbol: "BFUSD" },
    ],
  },
  {
    id: "oracle-data",
    name: "Oracle & Data",
    emoji: "🔮",
    description: "ตัวป้อนข้อมูลราคาจากโลกจริงเข้าสู่บล็อกเชน",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Chainlink", symbol: "LINK" },
      { name: "Pyth Network", symbol: "PYTH" },
      { name: "Band Protocol", symbol: "BAND" },
      { name: "API3", symbol: "API3" },
      { name: "Tellor", symbol: "TRB" },
      { name: "Numeraire", symbol: "NMR" },
      { name: "The Graph", symbol: "GRT" },
      { name: "Flux", symbol: "FLUX" },
      { name: "RedStone", symbol: "RED" },
    ],
  },
  {
    id: "storage-depin",
    name: "Storage & DePIN",
    emoji: "💾",
    description: "พื้นที่เก็บข้อมูลและโครงสร้างพื้นฐานกายภาพแบบกระจาย",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Filecoin", symbol: "FIL" },
      { name: "Arweave", symbol: "AR" },
      { name: "Storj", symbol: "STORJ" },
      { name: "Render", symbol: "RENDER" },
      { name: "IoTeX", symbol: "IOTX" },
      { name: "JasmyCoin", symbol: "JASMY" },
      { name: "Holo", symbol: "HOT" },
      { name: "Ankr", symbol: "ANKR" },
      { name: "Golem", symbol: "GLM" },
      { name: "Livepeer", symbol: "LPT" },
      { name: "Flux", symbol: "FLUX" },
      { name: "Powerledger", symbol: "POWR" },
      { name: "Siacoin", symbol: "SC" },
    ],
  },
  {
    id: "nft-metaverse",
    name: "NFT & Metaverse",
    emoji: "🖼️",
    description: "ตลาด NFT และโลกเสมือน",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "The Sandbox", symbol: "SAND" },
      { name: "Decentraland", symbol: "MANA" },
      { name: "ApeCoin", symbol: "APE" },
      { name: "Blur", symbol: "BLUR" },
      { name: "Enjin Coin", symbol: "ENJ" },
      { name: "Immutable", symbol: "IMX" },
      { name: "Gala", symbol: "GALA" },
      { name: "SuperRare", symbol: "RARE" },
      { name: "SuperVerse", symbol: "SUPER" },
      { name: "Illuvium", symbol: "ILV" },
      { name: "Pudgy Penguins", symbol: "PENGU" },
      { name: "Magic Eden", symbol: "ME" },
      { name: "Magic", symbol: "MAGIC" },
    ],
  },
  {
    id: "exchange-dex",
    name: "Exchange & DEX",
    emoji: "🔄",
    description: "โทเคนของกระดานเทรดทั้งแบบรวมศูนย์และกระจายศูนย์",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "BNB", symbol: "BNB" },
      { name: "Uniswap", symbol: "UNI" },
      { name: "PancakeSwap", symbol: "CAKE" },
      { name: "dYdX", symbol: "DYDX" },
      { name: "GMX", symbol: "GMX" },
      { name: "Jupiter", symbol: "JUP" },
      { name: "Raydium", symbol: "RAY" },
      { name: "1INCH", symbol: "1INCH" },
      { name: "SushiSwap", symbol: "SUSHI" },
      { name: "Trader Joe", symbol: "JOE" },
      { name: "DeXe", symbol: "DEXE" },
      { name: "Gains Network", symbol: "GNS" },
      { name: "0x", symbol: "ZRX" },
      { name: "Hashflow", symbol: "HFT" },
      { name: "Orca", symbol: "ORCA" },
      { name: "Aerodrome Finance", symbol: "AERO" },
    ],
  },
  {
    id: "liquid-staking",
    name: "Liquid Staking",
    emoji: "🌊",
    description: "สเตกแล้วยังเอาโทเคนไปใช้ต่อได้",
    url: "https://coinmarketcap.com/",
    coins: [
      { name: "Lido DAO", symbol: "LDO" },
      { name: "ether.fi", symbol: "ETHFI" },
      { name: "Jito", symbol: "JTO" },
      { name: "Ankr", symbol: "ANKR" },
      { name: "Rocket Pool", symbol: "RPL" },
      { name: "EigenLayer", symbol: "EIGEN" },
      { name: "Pendle", symbol: "PENDLE" },
      { name: "Solv", symbol: "SOLV" },
    ],
  },
];
